### ISSUE TITLE
Unable to read some PDB's

### ISSUE THREAD

**Issue by vatsan-madhavan** [Microsoft/cci#66]
We have been noticing that occasionally ILSpy & JustDecompile are unable to decompile C++/CLI assemblies like (WPF's) PresentationCore.dll.

Initially we thought that it might have been a compiler or a linker bug, but turns out that (a) the DLL is fine, and (b) the PDB is what these decompilers seem to have a problem with and (c) the PDB is also well formed per folks in the C++ compiler/linker teams. We also found that dotPeek is able to handle these assemblies ok.

The call stack presented by ILSpy seems to point to CCi.  Any ideas on what might be going on?

```
System.IndexOutOfRangeException: Index was outside the bounds of the array.
   at Microsoft.Cci.Pdb.BitAccess.ReadInt32(Int32& value)
   at Microsoft.Cci.Pdb.DbiSecCon..ctor(BitAccess bits)
   at Microsoft.Cci.Pdb.DbiModuleInfo..ctor(BitAccess bits, Boolean readStrings)
   at Microsoft.Cci.Pdb.PdbFile.LoadDbiStream(BitAccess bits, DbiModuleInfo[]& modules, DbiDbgHdr& header, Boolean readStrings)
   at Microsoft.Cci.Pdb.PdbFile.LoadFunctions(Stream read, Dictionary`2& tokenToSourceMapping, String& sourceServerData, Int32& age, Guid& guid)
   at Mono.Cecil.Pdb.NativePdbReader.PopulateFunctions()
   at Mono.Cecil.Pdb.NativePdbReader.ProcessDebugHeader(ImageDebugHeader header)
   at Mono.Cecil.ModuleDefinition.ReadSymbols(ISymbolReader reader, Boolean throwIfSymbolsAreNotMaching)
   at ICSharpCode.Decompiler.PdbProvider.Cecil.MonoCecilDebugInfoProvider..ctor(PEFile module, String pdbFileName, String description)
   at ICSharpCode.ILSpy.LoadedAssembly.LoadSymbols(PEFile module)
   at ICSharpCode.ILSpy.LoadedAssembly.LoadAssembly(Object state)
   at System.Threading.Tasks.Task`1.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()
```
Related: 
- [ILSpy issue ](https://github.com/icsharpcode/ILSpy/issues/1408#issue-404961643)
- [JustDecompile issue](https://github.com/telerik/JustDecompileEngine/issues/42) 

[not-bad-presentationcore.zip](https://github.com/Microsoft/cci/files/2819357/not-bad-presentationcore.zip)

**Comment by 0xd4d** [comment]
I noticed this:

- DBI stream seems to be empty.
- PDB GUID + AGE is 0c27088f-21e2-47d1-939f-9c91b8127173 & 4 in PDB, but 22d3b1ca-2ad9-4440-9ff8-b300f67efda0 & 1 in PE file's debug dir. They must match (https://github.com/dotnet/corefx/blob/master/src/System.Reflection.Metadata/specs/PE-COFF.md#codeview-debug-directory-entry-type-2). Is it the correct PDB file or did some tool forget to update the debug dir in the PE file?

**Comment by MichalStrehovsky** [comment]
This is the PDB reader in Cecil's fork of CCI: https://github.com/jbevain/cecil/blob/eea822cad4b6f320c9e1da642fcbc0c129b00a6e/symbols/pdb/Microsoft.Cci.Pdb/PdbFile.cs

**Comment by vatsan-madhavan** [comment]
@0xd4d - Thanks for noticing that and the hint. After some more investigations, I found that your hypothesis turned out to be the right one. The compiler generated PDB had clobbered the linker output PDB in our build system - a bug - which had gone unnoticed until now. We have now corrected the problem and the PDB's match - and ILSpy seems to be able to open the assembly without any problems.
